server:
    port: 8081
    servlet:
        context-path: /api/v1

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/db_test
        username: postgres
        password: backoffice
        poolsize: 30